spring.application.name=Smart-Study-Planner


# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/study_planner
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Format SQL (optional)
spring.jpa.properties.hibernate.format_sql=true